Assignment4
carolinafm216/FAAST pull request #12
Opened 2023-05-22 08:19 UTC by carolinafm216

2023-05-23 12:08 UTC, margarida-borbinha requested changes
You should have used the eurostat_life_expect.json which was in https://github.com/nosportugal/faast-foundations/blob/main/assignments/assignment_4/eurostat_life_expect.zip to test your json strategy

2023-05-23 12:08 UTC, margarida-borbinha requested changes
You should have used the eurostat_life_expect.json which was in https://github.com/nosportugal/faast-foundations/blob/main/assignments/assignment_4/eurostat_life_expect.zip to test your json strategy

2023-05-24 07:42 UTC, carolinafm216 commented on assignments/life_expectancy/tests/pyproject.toml
> +   "bad-classmethod-argument",
ok

2023-05-24 07:44 UTC, carolinafm216 commented on assignments/life_expectancy/Country.py
> +    ES = "ES"
ok

2023-05-24 07:46 UTC, carolinafm216 commented on assignments/life_expectancy/tests/test_load_save_data_new.py
> +        File_processor = file_processor(file_path, file_processor.CSVReadingStrategy())
ok

2023-05-24 07:46 UTC, carolinafm216 commented on assignments/life_expectancy/pyproject.toml
>  disable = [
ok

2023-05-24 07:47 UTC, carolinafm216 commented on assignments/life_expectancy/loading_saving_data.py
> +read_file_name = "life_expectancy_original.json"
ok

2023-05-24 07:47 UTC, carolinafm216 commented on assignments/life_expectancy/loading_saving_data.py
>  file_path = pathlib.Path(__file__).parent / "data" / read_file_name
ok

2023-05-24 08:19 UTC, carolinafm216 commented on assignments/life_expectancy/__init__.py
> +        File_processor = file_processor(file_path, JSONReadingStrategy())
ok

2023-05-24 08:31 UTC, carolinafm216 commented
feito!

2023-05-24 09:00 UTC, margarida-borbinha requested changes
Still have some unresolved comments

2023-05-24 09:00 UTC, margarida-borbinha requested changes
Still have some unresolved comments

2023-05-24 09:01 UTC, margarida-borbinha requested changes
Still have some unresolved comments

2023-05-24 10:31 UTC, carolinafm216 commented on assignments/life_expectancy/Country.py
> +    ES = "ES"
feito

2023-05-24 10:36 UTC, carolinafm216 commented on assignments/life_expectancy/tests/test_load_save_data_new.py
> +        File_Processor = file_processor(file_path, file_processor.CSVReadingStrategy())
Feito

2023-05-24 10:38 UTC, carolinafm216 commented on assignments/life_expectancy/tests/test_load_save_data_new.py
> +        pd.testing.assert_frame_equal(Raw_Actual, life_expectancy_filter_region)
ok

2023-05-24 10:40 UTC, carolinafm216 commented on assignments/life_expectancy/tests/test_country.py
> +    assert response == coutry_list_expected
I don't get what do you mean by this comment

2023-05-29 09:56 UTC, margarida-borbinha approved these changes

2023-05-29 13:03 UTC, carolinafm216 commented
Assigment 4

2023-05-29 13:03 UTC, merged