assignment_2 - Refactoring
carolinafm216/FAAST pull request #5
Opened 2023-03-13 18:00 UTC by carolinafm216

2023-03-15 12:14 UTC, margarida-borbinha commented
Your git workflow wasn't triggered to the refactoring branch
Your code isn't flake8 compliant
You could disable less pylint messages

2023-03-15 12:14 UTC, margarida-borbinha requested changes

2023-03-15 15:37 UTC, MrCordeiro requested changes

2023-03-15 15:37 UTC, MrCordeiro commented on assignments/life_expectancy/__init__.py
**suggestion**: move this to `main.py`

2023-03-15 15:37 UTC, MrCordeiro commented on assignments/life_expectancy/cleaning.py
>      df = df[['unit', 'sex', 'age', 'region', 'year', 'value']]
df=df
df = df

2023-03-15 15:37 UTC, MrCordeiro commented on assignments/life_expectancy/cleaning.py
>  def date_format(df):
```suggestion
def _convert_date_format(df: pd.DataFrame) -> pd.DataFrame:
```

2023-03-16 19:45 UTC, carolinafm216 commented on assignments/life_expectancy/tests/test_cleaning.py
>      #clean_data()
Feito

2023-03-16 20:04 UTC, carolinafm216 commented on assignments/life_expectancy/cleaning.py
> +    return filter_region(date_format(unpivot(df)), country)
feito

2023-03-16 20:08 UTC, carolinafm216 commented on assignments/life_expectancy/cleaning.py
>  def date_format(df):
feito

2023-03-16 20:11 UTC, carolinafm216 commented on assignments/life_expectancy/tests/test_cleaning.py
> +    save_data(clean_data(load_data(file_path), 'PT'))
feito

2023-03-16 20:12 UTC, carolinafm216 commented on assignments/life_expectancy/cleaning.py
> +    save_data(clean_data(load_data(file_path), args.country))
feito

2023-03-16 20:13 UTC, carolinafm216 commented on assignments/life_expectancy/cleaning.py
> +    with open(path, encoding="utf8") as file:
feito

2023-03-16 20:38 UTC, carolinafm216 commented on assignments/life_expectancy/cleaning.py
>                          value_vars=['2021 ','2020 ', '2019 ', '2018 ', '2017 ',
feito

2023-03-16 20:46 UTC, carolinafm216 commented on assignments/life_expectancy/cleaning.py
>      df = df[['unit', 'sex', 'age', 'region', 'year', 'value']]
feito (black)

2023-03-22 15:49 UTC, margarida-borbinha approved these changes

2023-05-08 09:05 UTC, merged